Frontend/HomeOwners.Web.UI/Controllers/MessageController.cs
using HomeOwners.Web.UI.Clients.CommunityMessages;
using HomeOwners.Web.UI.Clients.CommunityMessages.Requests;
using HomeOwners.Web.UI.Clients.Property;
using HomeOwners.Web.UI.Models;
using HomeOwners.Web.UI.ResponseModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace HomeOwners.Web.UI.Controllers;

public class MessageController : Controller
{
    private readonly ICommunityMessageClient _communityMessagesClient;
    private readonly ILogger<MessageController> _logger;

    public MessageController(ICommunityMessageClient messagesClient, IPropertyClient propertyClient, ILoggerFactory loggerFactory)
    {
        _communityMessagesClient = messagesClient;
        _logger = loggerFactory.CreateLogger<MessageController>();
    }

    [Authorize(Roles = "Administrator")]
    [Route("Message/Edit/{id}")]
    public async Task<IActionResult> Edit([FromRoute] long? id)
    {

        var message = await _communityMessagesClient.GetMessageByIdAsync(id.Value);

        var viewModel = new EditMessageViewModel()
        {
            MessageId = id,
            CommunityId = message.CommunityId,
            Message = message.Message
        };

        return View(viewModel);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost("Message/Edit/{id}")]
    public async Task<IActionResult> Edit(EditMessageViewModel model)
    {
        try
        {
            var request = new EditCommunityMessageRequest()
            {
                Id = model.MessageId,
                NewMessage = model.Message
            };

            var response = await _communityMessagesClient.EditMessageAsync(request);

            ViewBag.SuccessMessage = "Message edited successfully";
            return View(model);
        }
        catch (Refit.ApiException ex)
        {
            switch (ex.StatusCode)
            {
                case HttpStatusCode.BadRequest:
                    var errorResponse = await ex.GetContentAsAsync<BadRequestResponseModel>();

                    foreach (var item in errorResponse.ValidationErrors)
                    {
                        ModelState.AddModelError(string.Empty, item.Message);
                    }

                    break;

                case HttpStatusCode.NotFound:
                    ModelState.AddModelError(string.Empty, "Not Found");
                    break;

                default:
                    _logger.LogError(ex.Message);
                    ModelState.AddModelError(string.Empty, "Unexpected error occured");
                    break;
            }
            return View(model);
        }
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost("Message/Delete/{id}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(long id)
    {
        try
        {
            var response = await _communityMessagesClient.DeleteMessageByIdAsync(id);

            return RedirectToAction("Details", "Community", new { id = response.CommunityId });
        }
        catch (Refit.ApiException ex)
        {
            switch (ex.StatusCode)
            {
                case HttpStatusCode.BadRequest:
                    var errorResponse = await ex.GetContentAsAsync<BadRequestResponseModel>();

                    foreach (var item in errorResponse.ValidationErrors)
                    {
                        ModelState.AddModelError(string.Empty, item.Message);
                    }

                    break;

                case HttpStatusCode.NotFound:
                    ModelState.AddModelError(string.Empty, "Not Found");
                    break;

                default:
                    _logger.LogError(ex.Message);
                    ModelState.AddModelError(string.Empty, "Unexpected error occured");
                    break;
            }
            return BadRequest();
        }
    }
}

Frontend/HomeOwners.Web.UI/Views/Message/Edit.cshtml
@model EditMessageViewModel;

@{
    ViewData["Title"] = "Edit message";
}


<div class="container mt-5">
    <div class="card shadow-lg border-0 rounded-4">
        <div class="card-header bg-primary text-white rounded-top-4">
            <h3 class="mb-0"> Send a Community Message</h3>
        </div>
        <div class="card-body p-4">
            @if (ViewBag.SuccessMessage != null)
            {
                <div class="alert alert-success">
                    @ViewBag.SuccessMessage
                </div>
            }
            <form asp-controller="Message" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                <input type="hidden" name="MessageId" value="@Model.MessageId" />
                <input type="hidden" name="CommunityId" value="@Model.CommunityId" />

                <div class="mb-3">
                    <label asp-for="Message" class="form-label fw-bold"></label>
                    <input asp-for="Message" class="form-control shadow-sm" placeholder="Enter message" />
                    <span asp-validation-for="Message" class="text-danger"></span>
                </div>

                <div class="d-flex justify-content-between mt-4">
                    <a class="nav-link rounded bg-light shadow-sm text-dark mt-4" asp-area="" asp-controller="Community" asp-action="Details" asp-route-id="@Model.CommunityId">
                        Back to Community
                    </a>

                    <button type="submit" class="btn btn-success">
                        Edit
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>