Frontend/HomeOwners.Web.UI/Models/CommunityViewModel.cs
namespace HomeOwners.Web.UI.Models;

public class CommunityViewModel
{
    public long Id { get; set; }
    public string Name { get; set; }
    public int PropertiesCount { get; set; }
}

Frontend/HomeOwners.Web.UI/Models/CreateMeetingViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HomeOwners.Web.UI.Models;

public class CreateMeetingViewModel
{
    public long? CommunityId { get; set; }
    [Required]
    public string? Reason { get; set; }
    [Required]
    public DateTime? MeetingTime { get; set; }
}

Frontend/HomeOwners.Web.UI/Controllers/CommunityController.cs
using HomeOwners.Web.UI.Clients.Community;
using HomeOwners.Web.UI.Clients.Community.Requests;
using HomeOwners.Web.UI.Clients.CommunityMeetings;
using HomeOwners.Web.UI.Clients.CommunityMeetings.Requests;
using HomeOwners.Web.UI.Clients.CommunityMessages;
using HomeOwners.Web.UI.Clients.CommunityMessages.Requests;
using HomeOwners.Web.UI.Clients.Property;
using HomeOwners.Web.UI.Models;
using HomeOwners.Web.UI.ResponseModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;

namespace HomeOwners.Web.UI.Controllers;

public class CommunityController : Controller
{
    private readonly ICommunityMessageClient _messagesClient;
    private readonly ICommunityClient _communityClient;
    private readonly IPropertyClient _propertyClient;
    private readonly ICommunityMeetingClient _meetingClient;
    private readonly ILogger<CommunityController> _logger;

    public CommunityController(ICommunityClient communityClient,
        ICommunityMessageClient messagesClient,
        ICommunityMeetingClient meetingClient,
        IPropertyClient propertyClient,
        ILoggerFactory loggerFactory)
    {
        _messagesClient = messagesClient;
        _communityClient = communityClient;
        _propertyClient = propertyClient;
        _meetingClient = meetingClient;
        _logger = loggerFactory.CreateLogger<CommunityController>();
    }

    public IActionResult Index()
    {
        return View();
    }

    [Authorize]
    [Route("Community/Details/{id}")]
    public async Task<IActionResult> Details([FromRoute] long? id)
    {
        try
        {
            var requestModel = new GetPropertyRequest()
            {
                CommunityId = id,
                UserId = GetUserId()
            };

            var properties = await _propertyClient.GetCommunityPropertiesAsync(requestModel);

            var messages = await _messagesClient.GetMessagesAsync(id!.Value);

            var meetings = await _meetingClient.GetMeetingsAsync(id!.Value);

            var viewModel = new CommunityDetailsViewModel()
            {
                CommunityMessageViewModels = messages.Select(x => new CommunityMessageViewModel()
                {
                    Id = x.Id,
                    CommunityId = x.CommunityId,
                    CreateTimeStamp = x.CreateTimeStamp,
                    CreatorUserName = x.CreatorUserName,
                    LastUpdateTimeStamp = x.LastUpdateTimeStamp,
                    Message = x.Message,
                }).ToList(),
                PropertiesViewModels = properties.Select(x => new PropertyShortViewModel()
                {
                    Dues = x.Dues,
                    MonthlyDue = x.MonthlyDue,
                    OwnerEmail = x.OwnerEmail,
                    PropertyType = x.PropertyType,
                    Tenants = x.Tenants,
                }).ToList(),
                CommunityMeetingViewModels = meetings.Select(x => new CommunityMeetingViewModel()
                {
                    Id = x.Id,
                    CommunityId = x.CommunityId,
                    CreateTimeStamp = x.CreateTimeStamp,
                    LastUpdateTimeStamp = x.LastUpdateTimeStamp,
                    CreatorUserName = x.CreatorUserName,
                    MeetingTime = x.MeetingTime,
                    Reason = x.Reason,
                }).ToList(),
                CommunityId = id.Value
            };

            return View(viewModel);
        }
        catch (Refit.ApiException ex)
        {
            switch (ex.StatusCode)
            {
                case HttpStatusCode.BadRequest:
                    var errorResponse = await ex.GetContentAsAsync<BadRequestResponseModel>();

                    foreach (var item in errorResponse.ValidationErrors)
                    {
                        ModelState.AddModelError(string.Empty, item.Message);
                    }

                    break;

                case HttpStatusCode.NotFound:
                    _logger.LogWarning("Not found response received. Response content - {content}", ex.Content);
                    break;

                default:
                    _logger.LogError(ex.Message);
                    break;
            }

            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController));
        }
    }


    [Authorize(Roles = "Administrator")]
    [Route("Community/Meeting/{id}")]
    public IActionResult CreateMeeting([FromRoute] long? id)
    {
        var viewModel = new CreateMeetingViewModel()
        {
            CommunityId = id
        };

        return View(viewModel);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost("Community/Meeting/{id}")]
    public async Task<IActionResult> CreateMeeting(CreateMeetingViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        try
        {
            var request = new CreateMeetingRequest()
            {
                CommunityId = model.CommunityId,
                CreatorId = GetUserId(),
                MeetingTime = model.MeetingTime,
                Reason = model.Reason,
            };

            var response = await _meetingClient.CreateMeetingAsync(request);

            _logger.LogInformation("Successfully created meeting. Returned id - {meetingId}", response);
        }
        catch (Refit.ApiException ex)
        {
            switch (ex.StatusCode)
            {
                case HttpStatusCode.BadRequest:
                    var errorResponse = await ex.GetContentAsAsync<BadRequestResponseModel>();

                    foreach (var item in errorResponse.ValidationErrors)
                    {
                        ModelState.AddModelError(string.Empty, item.Message);
                    }

                    break;

                case HttpStatusCode.NotFound:
                    _logger.LogWarning("Not found response received. Response content - {content}", ex.Content);
                    break;

                default:
                    _logger.LogError(ex.Message);
                    break;
            }
        }

        return RedirectToAction("Details", "Community", new { id = model.CommunityId });
    }


    [Authorize(Roles = "Administrator")]
    [Route("Community/Message/{id}")]
    public IActionResult CreateMessage([FromRoute] long? id)
    {
        var viewModel = new CreateCommunityMessageViewModel()
        {
            CommunityId = id
        };

        return View(viewModel);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost("Community/Message/{id}")]
    public async Task<IActionResult> CreateMessage(CreateCommunityMessageViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        try
        {
            var request = new CreateCommunityMessageRequest()
            {
                CommunityId = model.CommunityId,
                CreatorId = GetUserId(),
                Message = model.Message,
            };

            var response = await _messagesClient.CreateMessageAsync(request);

            _logger.LogInformation("Successfully created community message. Returned id - {meetingId}", response);
        }
        catch (Refit.ApiException ex)
        {
            switch (ex.StatusCode)
            {
                case HttpStatusCode.BadRequest:
                    var errorResponse = await ex.GetContentAsAsync<BadRequestResponseModel>();

                    foreach (var item in errorResponse.ValidationErrors)
                    {
                        ModelState.AddModelError(string.Empty, item.Message);
                    }

                    break;

                case HttpStatusCode.NotFound:
                    _logger.LogWarning("Not found response received. Response content - {content}", ex.Content);
                    break;

                default:
                    _logger.LogError(ex.Message);
                    break;
            }
        }

        return RedirectToAction("Details", "Community", new { id = model.CommunityId });
    }

    private long GetUserId()
    {
        var idClaim = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier);

        if (idClaim == null)
            throw new ArgumentException("Failed to get IdClaim from within Authorize-only endpoint");

        return long.Parse(idClaim.Value);
    }
}

Frontend/HomeOwners.Web.UI/Controllers/MeetingController.cs
using HomeOwners.Web.UI.Clients.CommunityMeetings;
using HomeOwners.Web.UI.Clients.CommunityMessages.Requests;
using HomeOwners.Web.UI.Clients.CommunityMessages;
using HomeOwners.Web.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using HomeOwners.Web.UI.ResponseModels;
using Microsoft.AspNetCore.Authorization;
using HomeOwners.Web.UI.Clients.CommunityMeetings.Requests;

namespace HomeOwners.Web.UI.Controllers;

public class MeetingController : Controller
{
    private readonly ICommunityMeetingClient _meetingClient;
    private readonly ILogger<MeetingController> _logger;

    public MeetingController(ICommunityMeetingClient meetingClient, ILoggerFactory loggerFactory)
    {
        _meetingClient = meetingClient;
        _logger = loggerFactory.CreateLogger<MeetingController>();
    }

    [Authorize(Roles = "Administrator")]
    [Route("Meeting/Edit/{id}")]
    public async Task<IActionResult> Edit([FromRoute] long? id)
    {

        var message = await _meetingClient.GetMeetingByIdAsync(id.Value);

        var viewModel = new EditMeetingViewModel()
        {
            MeetingId = id,
            CommunityId = message.CommunityId,
            MeetingTime = message.MeetingTime,
            Reason = message.Reason,
        };

        return View(viewModel);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost("Meeting/Edit/{id}")]
    public async Task<IActionResult> Edit(EditMeetingViewModel model)
    {
        try
        {
            var request = new EditMeetingRequest()
            {
                Id = model.MeetingId,
                MeetingTime= model.MeetingTime,
                NewReason = model.Reason
            };

            var response = await _meetingClient.EditMeetingAsync(request);

            ViewBag.SuccessMessage = "Meeting edited successfully";
            return View(model);
        }
        catch (Refit.ApiException ex)
        {
            switch (ex.StatusCode)
            {
                case HttpStatusCode.BadRequest:
                    var errorResponse = await ex.GetContentAsAsync<BadRequestResponseModel>();

                    foreach (var item in errorResponse.ValidationErrors)
                    {
                        ModelState.AddModelError(string.Empty, item.Message);
                    }

                    break;

                case HttpStatusCode.NotFound:
                    ModelState.AddModelError(string.Empty, "Not Found");
                    break;

                default:
                    _logger.LogError(ex.Message);
                    ModelState.AddModelError(string.Empty, "Unexpected error occured");
                    break;
            }
            return View(model);
        }
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost("Meeting/Delete/{id}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(long id)
    {
        try
        {
            var response = await _meetingClient.DeleteMeetingByIdAsync(id);

            return RedirectToAction("Details", "Community", new { id = response.CommunityId });
        }
        catch (Refit.ApiException ex)
        {
            switch (ex.StatusCode)
            {
                case HttpStatusCode.BadRequest:
                    var errorResponse = await ex.GetContentAsAsync<BadRequestResponseModel>();

                    foreach (var item in errorResponse.ValidationErrors)
                    {
                        ModelState.AddModelError(string.Empty, item.Message);
                    }

                    break;

                case HttpStatusCode.NotFound:
                    ModelState.AddModelError(string.Empty, "Not Found");
                    break;

                default:
                    _logger.LogError(ex.Message);
                    ModelState.AddModelError(string.Empty, "Unexpected error occured");
                    break;
            }
            return BadRequest();
        }
    }
}

Frontend/HomeOwners.Web.UI/Views/Community/CreateMeeting.cshtml
@model HomeOwners.Web.UI.Models.CreateMeetingViewModel

@{
    ViewData["Title"] = "CreateCommunityMeeting";
}

<div class="container mt-5">
    <div class="card shadow-lg border-0 rounded-4">
        <div class="card-header bg-primary text-white rounded-top-4">
            <h3 class="mb-0"> Create Community Meeting</h3>
        </div>
        <div class="card-body p-4">
            <form asp-controller="Community" asp-action="CreateMeeting">
                <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                <input type="hidden" name="CommunityId" value="@Model.CommunityId" />

                <div class="mb-3">
                    <label asp-for="Reason" class="form-label fw-bold"></label>
                    <input asp-for="Reason" class="form-control shadow-sm" placeholder="Enter reason for meeting" />
                    <span asp-validation-for="Reason" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="MeetingTime" class="form-label fw-bold"></label>
                    <input asp-for="MeetingTime" type="datetime-local" class="form-control shadow-sm" />
                    <span asp-validation-for="MeetingTime" class="text-danger"></span>
                </div>

                <div class="d-flex justify-content-between mt-4">
                    <a href="@Url.Action("Details", "Community", new { id = Model.CommunityId })" class="btn btn-outline-secondary">
                        Back to Community
                    </a>
                    <button type="submit" class="btn btn-success">
                        Create Meeting
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

Frontend/HomeOwners.Web.UI/Views/Community/CreateMessage.cshtml
@model CreateCommunityMessageViewModel;

@{
    ViewData["Title"] = "CreateCommunityMessage";
}


<div class="container mt-5">
    <div class="card shadow-lg border-0 rounded-4">
        <div class="card-header bg-primary text-white rounded-top-4">
            <h3 class="mb-0"> Send a Community Message</h3>
        </div>
        <div class="card-body p-4">
            <form asp-controller="Community" asp-action="CreateMessage">
                <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                <input type="hidden" name="CommunityId" value="@Model.CommunityId" />

                <div class="mb-3">
                    <label asp-for="Message" class="form-label fw-bold"></label>
                    <input asp-for="Message" class="form-control shadow-sm" placeholder="Enter reason for meeting" />
                    <span asp-validation-for="Message" class="text-danger"></span>
                </div>

                <div class="d-flex justify-content-between mt-4">
                    <a href="@Url.Action("Details", "Community", new { id = Model.CommunityId })" class="btn btn-outline-secondary">
                        Back to Community
                    </a>
                    <button type="submit" class="btn btn-success">
                        Send
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

Frontend/HomeOwners.Web.UI/Views/Community/Details.cshtml
@model CommunityDetailsViewModel;

<div class="dashboard-container d-flex justify-content-center align-items-start gap-5 p-4">

    <div class="card-column d-flex flex-column gap-4" style="max-height: 80vh; width:30vw; overflow-y: auto;">
        <h3 class="text-center">Community Meetings</h3>

        @if (User.IsInRole("Administrator"))
        {
            <a href="@Url.Action("CreateMeeting", "Community", new { id = Model.CommunityId})" class="btn btn-outline-primary">
                Create Meeting
            </a>
        }
        <partial name="_MeetingsDisplay" model="@Model.CommunityMeetingViewModels"></partial>
    </div>

    <div class="message-feed" style="width: 50vw; max-height: 80vh; overflow-y: auto;">

        <h3 class="text-center">Message board</h3>

        @if (User.IsInRole("Administrator"))
        {
            <a href="@Url.Action("CreateMessage", "Community", new { id = Model.CommunityId})" class="btn btn-outline-primary">
                Create Message
            </a>
        }
        <partial name="_MessagesDisplay" model="@Model.CommunityMessageViewModels"></partial>
    </div>

    <div class="card-column d-flex flex-column gap-4" style="max-height: 80vh; width:20vw; overflow-y: auto;">
        <partial name="_PropertiesShortDisplay" model="@Model.PropertiesViewModels"></partial>
    </div>
</div>

Frontend/HomeOwners.Web.UI/Views/Community/_MeetingsDisplay.cshtml
@model IEnumerable<CommunityMeetingViewModel>

<div>
	@if (!Model.Any())
	{
		<div class="alert alert-warning text-center" role="alert">
			No meetings have been found for the community
		</div>
	}
	else
	{
		@foreach (var meeting in Model.OrderByDescending(x => x.MeetingTime))
		{
			<div class="bg-white border rounded-2 p-3 border-secondary-subtle w-100">
				<p>
					<strong>@meeting.CreatorUserName</strong> <span style="color: gray;">@meeting.CreateTimeStamp.ToString("yyyy-MM-dd HH:mm")</span>
					@if (meeting.LastUpdateTimeStamp != null)
					{
						<span class="text-secondary fst-italic ms-2" title="@meeting.LastUpdateTimeStamp.Value.ToString("yyyy-MM-dd HH:mm")">
							Edited
						</span>
					}
				</p>

				<p><strong>Meeting reason:</strong> @meeting.Reason</p>
				<p><strong>Meeting time (UTC):</strong> @meeting.MeetingTime.ToString("MMMM dd, yyyy 'at' HH:mm")</p>

				@if (User.IsInRole("Administrator"))
				{
					<a class="btn btn-sm btn-outline-info mt-2"
					   asp-controller="Meeting"
					   asp-action="Edit"
					   asp-route-id="@meeting.Id">
						Edit meeting
					</a>

					<form asp-controller="Meeting" asp-action="Delete" asp-route-id="@meeting.Id" method="post" class="d-inline">
						@Html.AntiForgeryToken()
						<button type="submit" class="btn btn-sm btn-outline-danger mt-2">
							Delete
						</button>
					</form>
				}
			</div>
		}
	}
</div>

Frontend/HomeOwners.Web.UI/Views/Community/_MessagesDisplay.cshtml
@model IEnumerable<CommunityMessageViewModel>

<div>
    @if (!Model.Any())
    {
        <div class="alert alert-warning text-center" role="alert">
            No messages have been found for the community
        </div>
    }
    else
    {
        @foreach (var msg in Model.OrderByDescending(x => x.CreateTimeStamp))
        {
            <div class="border-bottom border-secondary-subtle py-2">
                <p>
                    <strong>@msg.CreatorUserName</strong> <span style="color: gray;">@msg.CreateTimeStamp.ToString("yyyy-MM-dd HH:mm")</span>
                    @if (msg.LastUpdateTimeStamp != null)
                    {
                        <span class="text-secondary fst-italic ms-2" title="@msg.LastUpdateTimeStamp.Value.ToString("yyyy-MM-dd HH:mm")">
                            Edited
                        </span>
                    }
                </p>
                <p>@msg.Message</p>

                @if (User.IsInRole("Administrator"))
                {
                    <a class="btn btn-sm btn-outline-info mt-2"
                       asp-controller="Message"
                       asp-action="Edit"
                       asp-route-id="@msg.Id">
                        Change message
                    </a>

                    <form asp-controller="Message" asp-action="Delete" asp-route-id="@msg.Id" method="post" class="d-inline">
                        @Html.AntiForgeryToken()
                        <button type="submit" class="btn btn-sm btn-outline-danger mt-2">
                            Delete
                        </button>
                    </form>
                }
            </div>

        }
    }
</div>

Frontend/HomeOwners.Web.UI/Views/Community/_PropertiesShortDisplay.cshtml
@model IEnumerable<PropertyShortViewModel>

@foreach (var card in Model)
{
    <div class="bg-white border rounded-2 p-3 border-secondary-subtle w-100" style="word-wrap: break-word;">
        <p><strong>Property Type:</strong> @card.PropertyType.ToString()</p>
        <p><strong>Occupants:</strong> @card.Tenants</p>
        <p><strong>Total Dues:</strong> @card.Dues.ToString()</p>
        <p><strong>Monthly Dues:</strong> @card.MonthlyDue.ToString()</p>
        @if (User.IsInRole("Administrator"))
        {
            <p><strong>Property Contact email:</strong> @card.OwnerEmail</p>
        }
    </div>
}